[[constraint]]
  name = "cloud.google.com/go"
  source = "https://github.com/GoogleCloudPlatform/google-cloud-go.git"

# Used by Microsoft Azure Blob storage backend
[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "14.0.0"

# Used by Alibaba Cloud OSS storage backend
[[constraint]]
  name = "github.com/aliyun/aliyun-oss-go-sdk"
  version = "1.8.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.10.18"

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.2.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/urfave/cli"
  version = "1.20.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.5.0"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.8.2"

[prune]
  go-tests = true
  unused-packages = true
